### ISSUE TITLE
Repackage php dependency so as to not contain symlink references to external locations

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/php-dist#253]
### Background

Recently packit decided to validate against zip slipping (https://github.com/paketo-buildpacks/packit/pull/158). So any dependency that can potentially access parts of the file system outside of the target directory is a risk and its installation would result in an error. Thus, updates to packit (#230) and occam (#220) have been failing.

### Proposal

Repackage the PHP Dist tarball so that it does not have symlink references to external file locations.
See this thread (https://github.com/paketo-buildpacks/packit/issues/161#issuecomment-859125387) for further info.
PRs updating packit (#230) and occam (#220) should pass once this is resolved.

**Comment by thitch97** [comment]
As mentioned in the comment referenced above (https://github.com/paketo-buildpacks/packit/issues/161#issuecomment-859125387), we can modify the [code for packaging buildpack dependencies](https://github.com/cloudfoundry/binary-builder/blob/543c706d05f0245f476f47c7add22fbb35758761/lib/archive_recipe.rb) so that the built artifacts do not contain symlinks to external file locations.
